from django.http import JsonResponse
from django.contrib.auth.models import User
from actors.models import Actor
from awards.models import Award
from comments.models import GameComment, MovieComment, SerieComment
from consoles.models import Console
from developers.models import Developer
from directors.models import Director
from genres.models import Genre
from movie_producers.models import MovieProducer
from movies.models import Movie
from series.models import Serie
from videogames.models import Videogame

def create_initial_data(request):

  #usuarios Admin
  userAndy = User(username="AndySam", password="12345", first_name="Andy", last_name="Castillo", email="andy@gmail.com", is_staff=True)
  userAndy.save()
  userAndy.set_password("12345")
  userAndy.save()
  userMarco = User(username="marcof", password="12345678", first_name="Marco", last_name="Fuentes", email="marco@gmail.com", is_staff=True)
  userMarco.save()
  userMarco.set_password("12345678")
  userMarco.save()

  #Awards
  awardGoty = Award(name="Game Award", entity="The Game Awards", category="Juego del año", year=2019)
  awardGoty.save()
  awardBestMovie = Award(name="Oscar", entity="The Academy", category="Mejor película", year=2019)
  awardBestMovie.save()
  awardBestActionMovie = Award(name="Oscar", entity="The Academy", category="Mejor película de acción", year=2019)
  awardBestActionMovie.save()
  awardBestSerie = Award(name="Emmy", entity="Television Academy", category="Mejor serie", year=2019)
  awardBestSerie.save()
  awardBestActor2019 = Award(name="Oscar", entity="The Academy", category="Mejor actor", year=2019)
  awardBestActor2019.save()
  awardBestActress2019 = Award(name="Oscar", entity="The Academy", category="Mejor actriz", year=2019)
  awardBestActress2019.save()
  awardBestShooter = Award(name="Game Award", entity="The Game Awards", category="Mejor shooter", year=2019)
  awardBestShooter.save()
  awardBestDirector = Award(name="Oscar", entity="The Academy", category="Mejor director", year=2019)
  awardBestDirector.save()
  awardBestActor2018 = Award(name="Oscar", entity="The Academy", category="Mejor actor", year=2019)
  awardBestActor2018.save()
  awardBestActress2018 = Award(name="Oscar", entity="The Academy", category="Mejor actriz", year=2019)
  awardBestActress2018.save()

  #Consoles
  consoleXboxOne = Console(name="Xbox One",release_date="2013-11-22", brand="Microsoft")
  consoleXboxOne.save()
  consolePS4 = Console(name="PlayStation 4",release_date="2013-11-15", brand="Sony")
  consolePS4.save()
  consoleSwitch = Console(name="Switch",release_date="2017-03-03", brand="Nintendo")
  consoleSwitch.save()
  console64 = Console(name="Nintendo 64",release_date="1996-06-23", brand="Nintendo")
  console64.save()
  consoleXbox360 = Console(name="Xbox 360",release_date="2005-11-22", brand="Microsoft")
  consoleXbox360.save()
  consolePS3 = Console(name="PlayStation 3",release_date="2006-11-11", brand="Sony")
  consolePS3.save()
  consolePc = Console(name="PC",release_date="1950-09-21", brand="Variado")
  consolePc.save()

  #Géneros
  genreAction = Genre(name="Acción")
  genreAction.save()
  genreThriller = Genre(name="Thriller")
  genreThriller.save()
  genreAdventure = Genre(name="Aventura")
  genreAdventure.save()
  genreHorror = Genre(name="Horror")
  genreHorror.save()
  genreComedy = Genre(name="Comedia")
  genreComedy.save()
  genreRomantic = Genre(name="Romántico")
  genreRomantic.save()
  genreShooter = Genre(name="Disparos")
  genreShooter.save()
  genrePlatform = Genre(name="Plataformas")
  genrePlatform.save()
  genreMusical = Genre(name="Musical")
  genreMusical.save()
  genreDrama = Genre(name="Drama")
  genreDrama.save()
  genreSport = Genre(name="Deporte")
  genreSport.save()

  #Developers
  developerActivision= Developer(name="Activision", country="Estados Unidos", year_founded=1979)
  developerActivision.save()
  developerBlizzard= Developer(name="Blizzard", country="Estados Unidos", year_founded=1991)
  developerBlizzard.save()
  developerEA= Developer(name="Electronic Arts", country="Estados Unidos", year_founded=1982)
  developerEA.save()
  developerUbisoft= Developer(name="Ubisoft", country="Francia", year_founded=1986)
  developerUbisoft.save()
  developerNintendo= Developer(name="Nintendo", country="Japón", year_founded=1889)
  developerNintendo.save()
  developerRockstar= Developer(name="Rockstar Games", country="Estados Unidos", year_founded=1998)
  developerRockstar.save()

  #Movie producers
  movieProducerLucasfilm = MovieProducer(name="Lucasfilm", country="Estados Unidos", year_founded=1971)
  movieProducerLucasfilm.save()
  movieProducerMarvel = MovieProducer(name="Marvel Studios", country="Estados Unidos", year_founded=2007)
  movieProducerMarvel.save()
  movieProducerDisney = MovieProducer(name="Walt Disney Pictures", country="Estados Unidos", year_founded=1923)
  movieProducerDisney.save()
  movieProducerUniversal = MovieProducer(name="Universal Studios", country="Estados Unidos", year_founded=1912)
  movieProducerUniversal.save()
  movieProducerFox = MovieProducer(name="20th Century Fox", country="Estados Unidos", year_founded=1935)
  movieProducerFox.save()
  movieProducerColumbia = MovieProducer(name="Columbia Pictures", country="Estados Unidos", year_founded=1924)
  movieProducerColumbia.save()

 #Directores
  directorAnthony = Director(name="Anthony", lastName="Russo",birthDate="1970-02-03", birthPlace="Estados Unidos", netWorth="500000", height=1.70, nickname="Rus")
  directorAnthony.save()
  directorAnthony.awards.add(awardBestDirector)
  directorAnthony.save()
  directorSpielberg = Director(name="Steven", lastName="Spielberg",birthDate="1946-12-18", birthPlace="Estados Unidos", netWorth="1000000", height=1.80, nickname="Steve")
  directorSpielberg.save()
  directorSpielberg.awards.add(awardBestDirector)
  directorSpielberg.save()
  directorMartin = Director(name="Martin", lastName="Scorsese",birthDate="1942-11-17", birthPlace="Estados Unidos", netWorth="250000", height=1.75, nickname="Bart")
  directorMartin.save()
  directorLucas = Director(name="George", lastName="Lucas",birthDate="1944-05-14", birthPlace="Estados Unidos", netWorth="1100000", height=1.85, nickname="Luke")
  directorLucas.save()
  directorJohn = Director(name="John", lastName="Lasseter",birthDate="1957-01-12", birthPlace="Estados Unidos", netWorth="300000", height=1.77, nickname="Johnny")
  directorJohn.save()

  #Actores
  actorDiCaprio = Actor(name="Leonardo", lastName="DiCaprio", birthDate="1974-11-11", birthPlace="Estados Unidos", netWorth=1000000, height=1.85, nickname="Leo")
  actorDiCaprio.save()
  actorDiCaprio.awards.add(awardBestActor2018)
  actorDiCaprio.save()
  actorIronMan = Actor(name="Robert", lastName="Downey Jr", birthDate="1965-04-04", birthPlace="Estados Unidos", netWorth=900000, height=1.82, nickname="Iron Man")
  actorIronMan.save()
  actorIronMan.awards.add(awardBestActor2019)
  actorIronMan.save()
  actorRey = Actor(name="Diasy", lastName="Ridley", birthDate="1992-04-10", birthPlace="Inglaterra", netWorth=800000, height=1.80, nickname="Rey")
  actorRey.save()
  actorRey.awards.add(awardBestActress2018, awardBestActor2019)
  actorRey.save()
  actorOwen = Actor(name="Owen", lastName="Wilson", birthDate="1968-11-18", birthPlace="Estados Unidos", netWorth=750000, height=1.81, nickname="Wil")
  actorOwen.save()
  actorPratt = Actor(name="Chris", lastName="Pratt", birthDate="1979-06-21", birthPlace="Estados Unidos", netWorth=600000, height=1.90, nickname="Star Lord")
  actorPratt.save()
  actorSpiderMan = Actor(name="Tom", lastName="Holland", birthDate="1996-06-01", birthPlace="Inglaterra", netWorth=800000, height=1.73, nickname="Spider Man")
  actorSpiderMan.save()
  actorJennifer = Actor(name="Jennifer", lastName="Aniston", birthDate="1969-02-11", birthPlace="Estados Unidos", netWorth=600000, height=1.75, nickname="Jen")
  actorJennifer.save()
  actorJennifer.awards.add(awardBestActress2018)
  actorJennifer.save()

  #Comentarios peliculas
  commentAndy = MovieComment(text="Yo soy Iron Man", author=userAndy)
  commentAndy.save()
  commentMarco = MovieComment(text="Buenísima 4.5 ducks", author=userMarco)
  commentMarco.save()
  commentMarcoEndgame = MovieComment(text="Buenísima, Capitán América for life", author=userMarco)
  commentMarcoEndgame.save()

  #Películas
  movieEndgame = Movie(name="Endgame", rating=5.0, budget=3.5, duration=180.0, classification="PG-13", director= directorAnthony, producer=movieProducerMarvel)
  movieEndgame.save()
  movieEndgame.award.add(awardBestMovie, awardBestActionMovie)
  movieEndgame.save()
  movieEndgame.genres.add(genreAction)
  movieEndgame.save()
  movieEndgame.comments.add(commentAndy, commentMarcoEndgame)
  movieEndgame.save()
  movieEndgame.actors.add(actorPratt, actorIronMan)
  movieEndgame.save()
  movieStarWars9 = Movie(name="Star Wars: Episodio IX", rating=5.0, budget=3.0, duration=150.0, classification="PG-13", director= directorLucas, producer=movieProducerLucasfilm)
  movieStarWars9.save()
  movieStarWars9.award.add(awardBestMovie)
  movieStarWars9.save()
  movieStarWars9.genres.add(genreAction,genreAdventure)
  movieStarWars9.save()
  movieStarWars9.comments.add(commentMarco)
  movieStarWars9.save()
  movieStarWars9.actors.add(actorRey)
  movieStarWars9.save()
  movieCars = Movie(name="Cars", rating=5.0, budget=2.0, duration=90.0, classification="G", director= directorJohn, producer=movieProducerDisney)
  movieCars.save()
  movieCars.actors.add(actorOwen)
  movieCars.save()
  movieCars.genres.add(genreComedy)
  movieCars.save()
  movieWallStreet = Movie(name="The Wolf of Wall Street", rating=5.0, budget=1.0, duration=180.0, classification="R", director= directorMartin, producer=movieProducerFox)
  movieWallStreet.save()
  movieWallStreet.actors.add(actorDiCaprio)
  movieWallStreet.save()
  movieWallStreet.genres.add(genreComedy)
  movieWallStreet.save()
  movieJurassicPark = Movie(name="Jurassic World", rating=5.0, budget=1.5, duration=124.0, classification="PG-13", director= directorSpielberg, producer=movieProducerUniversal)
  movieJurassicPark.save()
  movieJurassicPark.actors.add(actorPratt)
  movieJurassicPark.save()
  movieJurassicPark.genres.add(genreAction, genreThriller)
  movieJurassicPark.save()
  movieSpiderMan = Movie(name="Spider-Man: Homecoming", rating=5.0, budget=2.5, duration=133.0, classification="PG-13", director= directorAnthony, producer=movieProducerMarvel)
  movieSpiderMan.save()
  movieSpiderMan.genres.add(genreAction, genreAdventure)
  movieSpiderMan.save()
  movieSpiderMan.actors.add(actorSpiderMan)
  movieSpiderMan.save()

  #Comentarios Series
  commentAndyFriends = SerieComment(text="The Big Bang Theory es mejor", author=userAndy)
  commentAndyFriends.save()
  commentMarcoFriends = SerieComment(text="Excelente", author=userMarco)
  commentMarcoFriends.save()
  commentAndyArrow = SerieComment(text="Muy buena serie", author=userAndy)
  commentAndyArrow.save()

  #Series
  serieFriends = Serie(name="Friends", rating=5.0, seasons=10, classification="TV-14", director=directorJohn)
  serieFriends.save()
  serieFriends.comments.add(commentAndyFriends, commentMarcoFriends)
  serieFriends.save()
  serieFriends.actors.add(actorJennifer)
  serieFriends.save()
  serieFriends.genres.add(genreComedy)
  serieFriends.save()
  serieFriends.awards.add(awardBestSerie)
  serieFriends.save()
  serieArrow = Serie(name="Arrow", rating=5.0, seasons=8, classification="TV-14", director=directorAnthony)
  serieArrow.save()
  serieArrow.comments.add(commentAndyArrow)
  serieArrow.save()
  serieArrow.genres.add(genreAction, genreAdventure)
  serieArrow.save()
  serieArrow.actors.add(actorSpiderMan)
  serieArrow.save()
  serieWitcher = Serie(name="The Witcher", rating=5.0, seasons=1, classification="TV-MA", director=directorSpielberg)
  serieWitcher.save()
  serieWitcher.genres.add(genreThriller, genreAction)
  serieWitcher.save()
  serieWitcher.actors.add(actorDiCaprio)
  serieWitcher.save()
  serieBigBang = Serie(name="The Big Bang theory", rating=5.0, seasons=12, classification="TV-14", director=directorMartin)
  serieBigBang.save()
  serieBigBang.genres.add(genreComedy)
  serieBigBang.save()
  serieBigBang.comments.add(commentAndyArrow)
  serieBigBang.save()
  serieBigBang.actors.add(actorOwen)
  serieBigBang.save()
  serieDrake = Serie(name="Drake & Josh", rating=5.0, seasons=4, classification="TV-Y7", director=directorMartin)
  serieDrake.save()
  serieDrake.genres.add(genreComedy)
  serieDrake.save()
  serieDrake.actors.add(actorPratt)
  serieDrake.save()
  serieGreys = Serie(name="Greys Anatomy", rating=5.0, seasons=17, classification="TV-14", director=directorJohn)
  serieGreys.save()
  serieGreys.genres.add(genreDrama)
  serieGreys.save()
  serieGreys.actors.add(actorRey)
  serieGreys.save()

  #Comentarios juegos
  commentCodAndy = GameComment(text="El mejor shooter", author = userAndy)
  commentCodAndy.save()
  commentCodMarco = GameComment(text="Perfecto, muy educativo y entretenido para los pequeñines", author= userMarco)
  commentCodMarco.save()
  commentOverwatch = GameComment(text="Me encanta", author=userMarco)
  commentOverwatch.save()

  #Juegos
  game = Videogame(title="Call of Duty: Modern Warfare", classification="M", release_date="2019-10-25", rating=5.0, developer=developerActivision)
  game.save()
  game.genres.add(genreAction, genreShooter)
  game.save()
  game.comments.add(commentCodMarco, commentCodAndy)
  game.save()
  game.consoles.add(consoleXboxOne, consolePS4, consolePc)
  game.save()
  game = Videogame(title="Overwatch", classification="T", release_date="2016-05-24", rating=5.0, developer=developerBlizzard)
  game.save()
  game.genres.add(genreAction, genreShooter)
  game.save()
  game.comments.add(commentOverwatch)
  game.save()
  game.consoles.add(consoleXboxOne, consolePS4, consolePc)
  game.save()
  game = Videogame(title="Super Mario Odyssey", classification="E10+", release_date="2017-10-27", rating=5.0, developer=developerNintendo)
  game.save()
  game.genres.add(genrePlatform, genreAdventure)
  game.save()
  game.consoles.add(consoleSwitch)
  game.save()
  game = Videogame(title="Fifa 20", classification="E", release_date="2019-09-27", rating=5.0, developer=developerEA)
  game.save()
  game.genres.add(genreSport)
  game.save()
  game.consoles.add(consoleSwitch, consoleXboxOne, consolePS4)
  game.save()
  game = Videogame(title="GTA V", classification="M", release_date="2013-09-17", rating=5.0, developer=developerRockstar)
  game.save()
  game.genres.add(genreAction, genreShooter)
  game.save()
  game.consoles.add(consoleXboxOne, consolePS4, consolePS3, consoleXbox360, consolePc)
  game.save()
  game = Videogame(title="Assassins Creed: Odyssey", classification="M", release_date="2018-10-05", rating=5.0, developer=developerUbisoft)
  game.save()
  game.genres.add(genreAdventure, genreAction)
  game.save()
  game.consoles.add(consoleXboxOne, consolePS4)
  game.save()
  game = Videogame(title="Mario Kart 64", classification="E", release_date="1996-12-14", rating=5.0, developer=developerNintendo)
  game.save()
  game.genres.add(genreSport)
  game.save()
  game.consoles.add(console64)
  game.save()
  
  data= {
        'Status': 'Ok',
        'Data': 'Data imported'
    }
  return JsonResponse(data)
