# Generated by Django 3.0.4 on 2020-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_award_category'),
        ('actors', '0002_actor_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='awards',
            field=models.ManyToManyField(blank=True, to='awards.Award'),
        ),
    ]
