# Generated by Django 3.0.4 on 2020-05-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directors', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('seasons', models.IntegerField()),
                ('classification', models.CharField(max_length=10)),
                ('actors', models.ManyToManyField(to='actors.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directors.Director')),
            ],
        ),
    ]
