# Generated by Django 3.0.4 on 2020-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('series', '0002_serie_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='comments',
            field=models.ManyToManyField(to='comments.SerieComment'),
        ),
    ]
