# Generated by Django 3.0.4 on 2020-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('series', '0003_serie_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='genres',
            field=models.ManyToManyField(to='genres.Genre'),
        ),
    ]
