# Generated by Django 3.0.4 on 2020-06-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_serie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='imageUrl',
            field=models.TextField(null=True),
        ),
    ]
