# Generated by Django 3.0.4 on 2020-05-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('consoles', '0001_initial'),
        ('developers', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comments', models.ManyToManyField(to='comments.GameComment')),
                ('consoles', models.ManyToManyField(to='consoles.Console')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer')),
                ('genres', models.ManyToManyField(to='genres.Genre')),
            ],
        ),
    ]
