# Generated by Django 3.0.4 on 2020-05-31 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('movie_producers', '0001_initial'),
        ('movies', '0003_movie_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(to='comments.MovieComment'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_producers.MovieProducer'),
        ),
    ]
