# Generated by Django 3.0.4 on 2020-06-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imageUrl',
            field=models.TextField(null=True),
        ),
    ]
