# Generated by Django 3.0.4 on 2020-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
